workflows:
  android-build:
    name: MajestyOS Build
    instance_type: mac_mini_m1
    scripts:
      - name: Find and Build MajestyOS
        script: | 
          # 1. Розпаковуємо все
          unzip *.zip
          
          # 2. Шукаємо, де лежить файл gradlew (він головний)
          GRADLEW_PATH=$(find . -name gradlew)
          GRADLEW_DIR=$(dirname "$GRADLEW_PATH")
          
          # 3. Переходимо в ту папку
          cd "$GRADLEW_DIR"
          
          # 4. Даємо права і запускаємо збірку
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
      
