workflows:
  android-build:
    name: MajestyOS Build
    instance_type: mac_mini_m1
    scripts:
      - name: Find and Build MajestyOS
        script: | 
          # 1. Розпаковуємо архів
          unzip *.zip
          
          # 2. Знаходимо ПАПКУ, де лежить gradlew
          GRADLEW_FILE=$(find . -name gradlew | head -n 1)
          PROJECT_ROOT=$(dirname "$GRADLEW_FILE")
          
          echo "Проект знайдено в: $PROJECT_ROOT"
          cd "$PROJECT_ROOT"
          
          # 3. Даємо права і запускаємо
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
      
